#!/bin/ash

SERVERLISTURL=https://api.nordvpn.com/v1/servers?limit=16384
SERVERSJSONFILE=/tmp/servers.json
SERVERSORIGFILE=/tmp/servers.orig
SERVERSLISTFILE=/tmp/servers.list
SERVERLOADSFILE=/tmp/servers.loads
SERVERKEYSFILE=/tmp/servers.keys

echo "[*] Getting servers..."

# Remove servers list file if it is empty
if [ -f "$SERVERSLISTFILE" ]; then
  SERVERS=`cat $SERVERSLISTFILE`
  if [ "$SERVERS" == "" ]; then
    rm $SERVERSLISTFILE
  fi
fi

# Update the NordVPN servers file if it is older than 1 hour
GETSERVERJSON=false
NOW=$(date +%s)
LIMIT=$((NOW - 60*60))
if [ ! -s "$SERVERSJSONFILE" ]; then
  GETSERVERJSON=true
else
  FILEDATE=$(ls --full-time -l "$SERVERSJSONFILE" | awk '{print $6" "$7}')
  FILETS=$(date -d "$FILEDATE" +%s)
  if [ "$FILETS" -lt "$LIMIT" ]; then
    GETSERVERJSON=true
  fi
fi

# Get NordVPN servers list (realtime data)
if [ "$GETSERVERJSON" == "true" ]; then
  echo "[*] Retrieving recent server list..."
  if [ -f "$SERVERSJSONFILE" ]; then
    rm $SERVERSJSONFILE
  fi
  wget -q -T 10 -O $SERVERSJSONFILE $SERVERLISTURL 2>/dev/null
  touch $SERVERSJSONFILE
fi

if [ ! -s "$SERVERLOADSFILE" ] || [ ! -s "$SERVERSLISTFILE" ]; then
  if [ -s $SERVERSJSONFILE ]; then

    # Make a backup of the orignal JSON file
    cp $SERVERSJSONFILE $SERVERSORIGFILE

    # Get filesize
    SERVERSJSONFILESIZE=$(wc -c < "$SERVERSJSONFILE") 2>/dev/null
    echo -e "\033[1;36m[>] Downloaded $SERVERSJSONFILESIZE bytes of server information\033[0m"

    # Parse JSON and write servers to file
    echo "[*] Parsing server loads..."
    grep -o '"hostname"[^"]*"[^}]*"load"[^0-9]*[0-9][0-9]*' $SERVERSJSONFILE | \
    sed 's/"hostname":"\([^".]*\)[^"]*","load":\([0-9][0-9]*\)/\1:\2/' > $SERVERLOADSFILE
  else
    echo -e "\033[0;33m[!] Couldn't retrieve servers list\033[0m"

    # Restore original JSON backup
    if [ -r $SERVERSORIGFILE ]; then
      cp $SERVERSJSONFILE $SERVERSORIGFILE
      if [ -r $SERVERSJSONFILE]; then
        SERVERSJSONFILESIZE=$(wc -c < "$SERVERSJSONFILE") 2>/dev/null
        echo -e "\033[1;36m[>] Restored $SERVERSJSONFILESIZE bytes of server information\033[0m"
      fi
    fi
  fi
fi

PARSEKEYS=false
NOW=$(date +%s)
LIMIT=$((NOW - 60*60*24))
if [ ! -s "$SERVERKEYSFILE" ] || [ ! -s $SERVERSLISTFILE ]; then
  PARSEKEYS=true
else
  FILEDATE=$(ls --full-time -l "$SERVERKEYSFILE" | awk '{print $6" "$7}')
  FILETS=$(date -d "$FILEDATE" +%s)
  if [ "$FILETS" -lt "$LIMIT" ]; then
    PARSEKEYS=true
  fi
fi

if [ "$PARSEKEYS" == "true" ]; then

  if [ -f "$SERVERKEYSFILE" ]; then
    rm $SERVERKEYSFILE
  fi

 # Parse public keys from JSON to file if keys file is older than 1 day
  echo "[*] Parsing public keys..."
    awk '
    BEGIN { RS = "\"station\""; FS = "\"" }
    {
      for (i = 1; i <= NF; i++) {
        if ($i == "hostname") {
          hostname_full = $(i+2)
          split(hostname_full, arr, ".")
          hostname = arr[1]
        }
        if ($i == "value" && $(i-2) == "public_key") {
          public_key = $(i+2)
        }
      }
      if (hostname && public_key) {
        print hostname ":" public_key
        hostname = ""
        public_key = ""
      }
    }
  ' "$SERVERSJSONFILE" > "$SERVERKEYSFILE"

  # Create file with sorted server names
  echo "[*] Sorting server list..."
  sed 's/:.*//' $SERVERKEYSFILE | sort -u > $SERVERSLISTFILE
  touch $SERVERSLISTFILE
fi