#!/bin/ash

PACKAGES="wireguard-tools,kmod-wireguard,luci-proto-wireguard,luci"

# Add script directory to PATH if it's not there yet
SCRIPTDIR=$(cd "$(dirname "$0")" && pwd)
if ! grep -q "$SCRIPTDIR" /etc/profile 2>/dev/null; then
	echo "[*] Adding scripts directory to PATH..."
	{
    echo ""
    echo "# Added by NordVPN WireGuard scripts installer on $(date)"
    echo "PATH=\$PATH:$SCRIPTDIR"
    echo "export PATH"
  } >> /etc/profile
fi

# Find scripts without executable flag and make them executable
for FILE in "$SCRIPTDIR"/*; do
  [ -f "$FILE" ] || continue
  if [ ! -x "$FILE" ]; then
    echo "[*] Making $FILE executable..."
		chmod +x $FILE
    break
  fi
done

# Install missing packages
UPDATEDREPO=false
IFS=','
for package in $PACKAGES; do
	opkg status $package >/dev/null 2>&1
	if [ ! $? -eq 0 ]; then
		echo "[*] Installing $package..."
		if [ "$UPDATEDREPO" == "false" ]; then
			opkg update
			UPDATEDREPO=true
		fi
	  opkg install $package 2>/dev/null
	fi
done

# generate new connection key pair
if [ ! -f "/etc/wireguard/privatekey" ] || [ ! -f "/etc/wireguard/publickey" ]; then
	echo "[*] Generating WireGuard key pair..."
	wg genkey > /etc/wireguard/privatekey 2>/dev/null
	wg pubkey < /etc/wireguard/privatekey > /etc/wireguard/publickey 2>/dev/null
fi

# Load master config
source $SCRIPTDIR/config/master_config

# ask user for private key if not done yet
if [ ! -f "$SCRIPTDIR/config/my_config" ]; then
	printf "Please enter your NordVPN private key: "
	read PRIVATEKEY
	cp "$SCRIPTDIR/config/master_config" \
	"$SCRIPTDIR/config/my_config" || exit 1
	sed -i "s/^CLIENTPRIVATEKEY=.*/CLIENTPRIVATEKEY=\"$PRIVATEKEY\"/" \
	"$SCRIPTDIR/config/my_config"
fi

